import Head from "next/head";
import Header from "../components/Header";
import LeftSideBar from "../components/LeftSideBar";
import PostFeed from "../components/PostFeed";
import RightSideBar from "../components/RightSideBar";

export default function Home() {
  return (
    <div className="h-screen flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="flex space-x-5 bg-[#282828] flex-1">
        <LeftSideBar />
        <PostFeed />
        <RightSideBar />
      </main>
    </div>
  );
}
